### ISSUE TITLE
[10.0] stock_operating_unit raise error when create receipts directly

### ISSUE THREAD

**Issue by repodevs** [OCA/operating-unit#65]
Create receipts (stock picking) directly (not from PO) will show error

Open Inventory Dashboard then create new transfer from receipts

![inventory odoo](https://cloud.githubusercontent.com/assets/13567128/23954644/70578136-09ca-11e7-96c0-c7d392d89ef1.png)

Will show error 
![inventory_new _odoo](https://cloud.githubusercontent.com/assets/13567128/23954696/947baa2e-09ca-11e7-9777-93956e38c590.png)

Testing using this runbot https://runbot.odoo-community.org/runbot/213/10.0

**Comment by ccandito** [comment]
DEar All,
I've implemented the last code of stock operating unit, but the error has occurred again.
the system log:
Regards
claudio candito 

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 885, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 5494, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 5392, in _onchange_eval
    method_res = method(self)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/stock_operating_unit/model/stock.py", line 126, in onchange_picking_type
    @api.constrains('operating_unit_id', 'company_id')
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by repodevs** [comment]
Fixed on #66
