### ISSUE TITLE
stock operating unit does not work for consume movement created directly

### ISSUE THREAD

**Issue by ccandito** [OCA/operating-unit#74]
Dear All,
I've tried to create a manual consume stock movement; by evaluating the picking type a short dump occurred (the related log is reported below). I've noticed also this doesn't occur by removing the app stock operating unit.
thanks in advance
claudio candito
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 885, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 5494, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 5392, in _onchange_eval
    method_res = method(self)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/stock_operating_unit/model/stock.py", line 126, in onchange_picking_type
    res['value']['operating_unit_id'] = unit.id
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by AaronHForgeFlow** [comment]
Hi @ccandito That is fixed already (https://github.com/OCA/operating-unit/issues/65). You just need to pull the latest code.
